name: 'retail_dbt_project'
version: '1.0.0'
config-version: 2

profile: 'default'

on-run-end:
  - "{{ log_model_runs(results) }}"

models:
  retail_dbt_project:

    staging:
      +schema: staging
      +materialized: view

    marts:
      +schema: mart
      +materialized: table

    intermediate:
      +schema: intermediate
      +materialized: table
    
    reporting:
        +schema: reporting
        +materialized: table  