version: 2

models:

  - name: dim_products

    columns:

      - name: product_sk
        tests:
          - not_null

      - name: product_id
        tests:
          - not_null

      - name: current_flag
        tests:
          - not_null

      - name: effective_date
        tests:
          - not_null

      - name: expiry_date
        tests:
          - not_null