version: 2

sources:
  - name: raw
    database: RETAIL_DWH
    schema: RAW

    tables:
      - name: ORDERS
      - name: RETURNS
      - name: CUSTOMERS
      - name: PRODUCTS
      - name: ORDER_ITEMS
      - name: PAYMENTS
      - name: INVENTORY